sdr:
  frequency: 98.5e6  # Target frequency (e.g., FM station)
  sample_rate: 2.4e6
  gain: auto
audio:
  output_dir: data/audio
  filename: captured_audio.wav
ai:
  whisper_model: base
  summarizer_model: t5-small
logging:
  log_file: logs/airbriefer.log